### ISSUE TITLE
cannot change default key

### ISSUE THREAD

**Issue by DavidSie** [test-kitchen/kitchen-openstack#129]
Hi I have my kitchen settings
```
---
driver:
  name: openstack
  openstack_username: <%= ENV['OS_USERNAME'] %>
  openstack_api_key: '<%= ENV['OS_PASSWORD'] %>'
  openstack_auth_url: "<%= ENV['OS_AUTH_URL'] %>/tokens"
  require_chef_omnibus: true 
  image_ref: CentOS-6.6
  flavor_ref: m1.large
  network_ref: SOME_NETWORK
  key_name: default_key

transport:
   ssh_key: 'PATH_TO_DEFAULT_KEY'

...(and some more)
```

but I see in logs that kitchen uses only "id_rsa" key 
can you help me with that 

here is a log
```
D      [SSH] opening connection to SOME_USER@SOMEIP<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>22, :compression=>true, :compression_level=>6, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :keys_only=>true, :keys=>["DEFAULT_PATH/id_rsa"], :auth_methods=>["publickey"]}>

```

**Comment by DavidSie** [comment]
Hi this configuration finds my key 

```
---
driver:
  name: openstack
  openstack_username: <%= ENV['OS_USERNAME'] %>
  openstack_api_key: '<%= ENV['OS_PASSWORD'] %>'
  openstack_auth_url: "<%= ENV['OS_AUTH_URL'] %>/tokens"
  require_chef_omnibus: true 
  image_ref: CentOS-6.6
  flavor_ref: m1.large
  network_ref: SOME_NETWORK
  key_name: default_key
  private_key_path: 'PATH_TO_KEY'



transport:
   ssh_key: 'PATH_TO_KEY'


platforms:
  - name: centos-6.6
    transport:
      username: USERNAME
      ssh_key: 'PATH_TO_KEY'
security_groups:
  - ssh

suites:
  - name: openjdk-6
    includes:
      - centos-6.6
    run_list:
      - recipe[java::default]

```

now I have to find which 2 PATH_TO_KEY I can delete
