### ISSUE TITLE
Volume: create new, attach existing, make from snapshot (seems not working)

### ISSUE THREAD

**Issue by styk-tv** [test-kitchen/kitchen-openstack#131]
Tried both:

```
 1. kitchen-openstack-2.1.1
 2. kitchen-openstack-2.2.0.pre.1
``` 

tried adding adding block_device_mappings: section to .kitchen.yml
under root node, driver node and driver_config node just to make sure

tried making brand new, from snapshot, attach existing with no success. tried based on example settings provided in README.me but also other combinations.

tried with device vdb and vda (since there is boot drive already)

Each time the driver doesn't display a single volume message (from source some messages should appear) when creating the instance (kitchen create) It does the instance, confirms winrm (windows) and exists. Obviously I don't mean windows mounting or anything like that. I mean from the perspective of openstack, I have not found a way to attach any form of volume during kitchen create making new instance.

```
block_device_mappings:
     make_volume: true
     snapshot_id: 2b449f7c-181d-4867-ba80-8843d6c0f56d
     device_name: vdb
     availability_zone: nova
     delete_on_termination: true
     creation_timeout: 120
```

also tried make_volume=false, volume_id=,volume_size= combinations

Any hints would be greatly appreciated. It seems block_device_mappings is not being hit at all.

P.
