### ISSUE TITLE
SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A (OpenSSL::SSL::SSLError)

### ISSUE THREAD

**Issue by cyberflow** [test-kitchen/kitchen-openstack#132]
Hellow, 
I have error when i try to use openstack driver for test-kitchen:
```
$ kitchen converge default-ubuntu-1404
-----> Starting Kitchen (v1.4.2)
D      Berksfile found at /Users/cyberflow/git/cookbooks/wz-influxdb/Berksfile, loading Berkshelf
D      Berkshelf 4.0.1 library loaded
-----> Creating <default-ubuntu-1404>...
>>>>>> Create failed on instance <default-ubuntu-1404>.
>>>>>> Please see .kitchen/logs/default-ubuntu-1404.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A (OpenSSL::SSL::SSLError)
>>>>>> ----------------------
D      Create failed on instance <default-ubuntu-1404>.
D      ------Exception-------
D      Class: Kitchen::InstanceFailure
D      Message: Create failed on instance <default-ubuntu-1404>.  Please see .kitchen/logs/default-ubuntu-1404.log for more details
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A (OpenSSL::SSL::SSLError)
D      ------Backtrace-------
D      /Library/Ruby/Gems/2.0.0/gems/kitchen-openstack-2.2.0/lib/kitchen/driver/openstack.rb:118:in `rescue in create'
D      /Library/Ruby/Gems/2.0.0/gems/kitchen-openstack-2.2.0/lib/kitchen/driver/openstack.rb:91:in `create'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:424:in `public_send'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:424:in `block in perform_action'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:488:in `call'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:488:in `synchronize_or_call'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:453:in `block in action'
D      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/benchmark.rb:281:in `measure'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:452:in `action'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:424:in `perform_action'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:352:in `create_action'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:341:in `block in transition_to'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:340:in `each'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:340:in `transition_to'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:138:in `converge'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/command.rb:176:in `public_send'
D      /Library/Ruby/Gems/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'
D      ----------------------
```

```
$ gem list | grep kitchen
kitchen-openstack (2.2.0)
test-kitchen (1.4.2)
```

How i can fix this problem?
Thanks.

**Comment by jjasghar** [comment]
Hi!

So that's coming from your OpenStack instance. Have you updated changed your SSL certs recently?

This is a [stackoverflow](http://stackoverflow.com/questions/25814210/opensslsslsslerror-ssl-connect-syscall-returned-5-errno-0-state-sslv3-read) answer on what's happening.

**Comment by jjasghar** [comment]
According to the answer, it's due to your version of OpenSSL.

**Comment by cyberflow** [comment]
update ruby from 2.0.0 to 2.1.2 and `bundle install` solve this problem.
Thanks.

**Comment by reddybathina** [comment]
I am facing the same issue, but the issue still there even after upgrading ruby and openssl.

```
[root@dev01 workspace]# kitchen converge
-----> Starting Kitchen (v1.6.0)
-----> Creating <default-ubuntu-1404>...
>>>>>> Create failed on instance <default-ubuntu-1404>.
>>>>>> Please see .kitchen/logs/default-ubuntu-1404.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read 
server hello A (OpenSSL::SSL::SSLError)
>>>>>> ----------------------
[root@dev01 workspace]#
```

```
[root@dev01 workspace]# ruby --version
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
[root@dev01 workspace]# gem list | egrep 'berkshelf|kitchen|openssl'
berkshelf (4.3.1)
berkshelf-api-client (2.0.2)
kitchen-ec2 (1.0.0)
kitchen-openstack (3.0.0)
openssl (0.2.0)
ruby-hmac-openssl (0.1.0)
rubysl-openssl (2.8.0)
test-kitchen (1.6.0)
[root@dev01 workspace]#
```

**Comment by jjasghar** [comment]
@reddybathina yeah something from your openstack instance is throwing this error. You have a newer version of ruby, which is good. what's the version of openssl that version of ruby is using?

**Comment by reddybathina** [comment]
```
[root@dev01 workspace]# openssl version
OpenSSL 1.0.1s-fips  1 Mar 2016
[root@dev01 workspace]#
```

**Comment by jjasghar** [comment]
can you run: ` ruby -ropenssl -e 'puts OpenSSL::OPENSSL_VERSION'` to verify please?

**Comment by reddybathina** [comment]
```
[root@dev01 workspace]# ruby -ropenssl -e 'puts OpenSSL::OPENSSL_VERSION'
OpenSSL 1.0.1s  1 Mar 2016
[root@dev01 workspace]#
```

**Comment by reddybathina** [comment]
is there a posibility to add SSL Version information in kitchen.yml file, like similar to "ssl_config.ssl_version = :SSLv23"

**Comment by jjasghar** [comment]
That's upstream test-kitchen, i'd ask there. /cc @cheeseplus @mwrock maybe yall know?

From those two checks you shouldn't be having SSL issues at all. I don't know what to tell you.

**Comment by mwrock** [comment]
I've seen similar errors from kitchen's berkshelf install on windows hosts. Is this a windows host talking to an openstack instance? Usually if you have chefdk installed, that takes care of this (but not always). I have manually fixed it before by:

1. Downloading an updated certs bundle from `http://curl.haxx.se/ca/cacert.pem`: `Invoke-WebRequest -Uri http://curl.haxx.se/ca/cacert.pem -OutFile c:\projects\kitchen-machine\certs.pem`
2. Assigning the local file to the `SSL_CERT_FILE` environment variable.

But this all assumes you are running on windows.

**Comment by reddybathina** [comment]
I am using Linux operating system [ centos7 ].
And want to inform that I am also using proxy.
Sample kitchen.yml file.

```
[root@dev01 workspace]# cat .kitchen.yml

---
driver:
  name: openstack
  openstack_username: xxxxxxx
  openstack_api_key: xxxxxx # OpenStack Password
  openstack_auth_url: https://xxxxxxxx:5000/v2.0/tokens
  openstack_tenant: testing
  disable_ssl_validation: true
  require_chef_omnibus: true
  image_ref:  ova-ubuntu1404
  flavor_ref: m1.small
  network_ref: net1
  key_name: key_1
  private_key_path: /var/lib/jenkins/.ssh/key_1.pem
  public_key_path: /var/lib/jenkins/.ssh/key_1.pub
  security_groups:
  - ssh-in

transport:
  ssh_key: /var/lib/jenkins/.ssh/key_1.pem
  username: ubuntu

provisioner:
  name: chef_solo
  http_proxy: http://proxy.aimsnew.com:80
  https_proxy: http://proxy.aimsnew.com:80

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[test01::default]
    attributes:
[root@dev01 workspace]#
```
