### ISSUE TITLE
Password value in transport is not used in driver

### ISSUE THREAD

**Issue by josh-barker** [test-kitchen/kitchen-openstack#133]
Hi,

Previously I was using an older version of the kitchen-openstack plugin and specified the ssh username and password like so:
```yml
---
driver
  name: openstack
...
platforms:
  - name: rhel6
    driver:      
      image_ref: rhel6_image
      username: root
      password: password
```

However, when I upgraded to 2.2.0 I'm prompted for the root password.
```bash
> kitchen create
-----> Creating <default-rhel6>...
       OpenStack instance with ID of <openstack-id> is ready.
       Waiting for network information to be available...
       Waiting for server to be ready...
       Waiting for SSH service on [ip_address]:22, retrying in 3 seconds
       Waiting for SSH service on [ip_address]:22, retrying in 3 seconds
root@[ip_address]'s password: 
       [SSH] Established
       Using public SSH key </home/me/.ssh/id_rsa.pub>
       Using private SSH key </home/me/.ssh/id_rsa>
       Setting up SSH access for key </home/me/.ssh/id_rsa.pub>
       Adding OpenStack hint for ohai
       Finished creating <default-rhel6> (1m35.68s).
-----> Kitchen is finished. (1m45.54s)
```

I did notice in the readme that the SSH username/password has been deprecated and should be specified in the transport. 
So I changed it to the following:
```yml
---
driver:
  name: openstack
  ...

platforms:
  - name: rhel6
    driver:      
      image_ref: rhel6_image
    transport:
      username: root
      password: rhel_password
  ...
```
However, I still get asked for the root password:
```bash
> kitchen create
-----> Creating <default-rhel6>...
       OpenStack instance with ID of <openstack-id> is ready.
       Waiting for network information to be available...
       Waiting for server to be ready...
       Waiting for SSH service on [ip_address]:22, retrying in 3 seconds
       Waiting for SSH service on [ip_address]:22, retrying in 3 seconds
       [SSH] Established
       Using public SSH key </home/me/.ssh/id_rsa.pub>
       Using private SSH key </home/me/.ssh/id_rsa>
       Setting up SSH access for key </home/me/.ssh/id_rsa.pub>
root@[ip_address]'s password: 
       Adding OpenStack hint for ohai
       Finished creating <default-rhel6> (1m35.68s).
-----> Kitchen is finished. (1m45.54s)
```

I'm wondering if I'm missing something for the configuration, or is there a bug?

I did find that when I specified the password both in the driver and the transport sections it worked, but that's not ideal.

Cheers
