### ISSUE TITLE
Permission Denied on kitchen runs after first

### ISSUE THREAD

**Issue by qubitrenegade** [test-kitchen/kitchen-openstack#146]
Hello,

I am receiving an error on any kitchen converge or kitchen verify runs after the inital run:

```
$ kitchen converge
-----> Starting Kitchen (v1.8.0)
[2016-06-09T13:03:05-06:00] WARN: Ohai::Config[:log_level] is set. Ohai::Config[:log_level] is deprecated and will be removed in future releases of ohai. Use ohai.log_level in your configuration file to configure :log_level for ohai.
[2016-06-09T13:03:05-06:00] WARN: Ohai::Config[:log_location] is set. Ohai::Config[:log_location] is deprecated and will be removed in future releases of ohai. Use ohai.log_location in your configuration file to configure :log_location for ohai.
[2016-06-09T13:03:05-06:00] WARN: Ohai::Config[:log_level] is set. Ohai::Config[:log_level] is deprecated and will be removed in future releases of ohai. Use ohai.log_level in your configuration file to configure :log_level for ohai.
[2016-06-09T13:03:05-06:00] WARN: Ohai::Config[:log_location] is set. Ohai::Config[:log_location] is deprecated and will be removed in future releases of ohai. Use ohai.log_location in your configuration file to configure :log_location for ohai.
-----> Converging <default-centos-65>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 4.3.3...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Chef Omnibus installation detected (install only if missing)
       Transferring files to <default-centos>
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: [scp: /tmp/kitchen/cookbooks: Permission denied
]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

```

My kitchen config is as follows:

```
---
driver:
  openstack_username: <%= ENV['OS_USERNAME'] %>
  openstack_api_key: <%= ENV['OS_PASSWORD'] %>
  openstack_auth_url: <%= "#{ENV['OS_AUTH_URL']}/tokens" %>
  openstack_tenant: <%= ENV['OS_TENANT'] %>
  key_name: <%= ENV['OS_KEY_NAME'] %>
  floating_ip_pool: <%= ENV['OS_IP_POOL'] %>
  image_ref: <%= ENV['OS_IMAGE'] %>
  flavor_ref: <%= ENV['OS_FLAVOR_REF'] %>
  require_chef_omnibus: true
  disable_ssl_validation: true
  network_ref: <%= ENV['OS_NETWORK_REF'] %>
  security_groups:
    - <%= ENV['OS_SECGROUP'] %>

transport:
  username: centos
  password: CentOS

provisioner:
  name: chef_zero

platforms:
  - name: centos

suites:
  - name: default
    driver_plugin: openstack

    # Edit this to reflect the recipes/cookbooks you're testing
    run_list:
      - recipe[my_chefclient::default]
    attributes:
      chef_client:
        conf_dir: '/tmp/kitchen'
```

As this is openstack using cloud-init I'm unable to login as root...

Any ideas how to fix this?  Or is this a problem with the driver itself?

Thanks!
