### ISSUE TITLE
The request you have made requires authentication

### ISSUE THREAD

**Issue by ssirobertreilly** [test-kitchen/kitchen-openstack#167]
Hi, I am trying to use test kitchen with out open stack, I get the following error 
```
E, [2017-04-10T11:01:35.384245 #15129] ERROR -- default-centos-72: Message: Expected([201]) <=> Actual(401 Unauthorized)
excon.error.response
  :body          => "{\"error\": {\"message\": \"The request you have made requires authentication.\", \"code\": 401, \"title\": \"Unauthorized\"}}"
  :cookies       => [
  ]
  :headers       => {
    "Content-Length"         => "114"
    "Content-Type"           => "application/json"
    "Date"                   => "Mon, 10 Apr 2017 15:01:35 GMT"
    "Server"                 => "Apache/2.4.6 (Red Hat Enterprise Linux) mod_wsgi/3.4 Python/2.7.5"
    "Vary"                   => "X-Auth-Token"
    "WWW-Authenticate"       => "Keystone uri=\"https://xxx:5000\""
    "x-openstack-request-id" => "req-16dc72e6-c904-4e35-98ff-570ddbbe0df0"
  }
  :host          => "xx-xx.xx.xx.net"
  :local_address => "xx"
  :local_port    => 58494
  :path          => "/v3/auth/tokens"
  :port          => 5000
  :reason_phrase => "Unauthorized"
  :remote_ip     => "xx"
  :status        => 401
  :status_line   => "HTTP/1.1 401 Unauthorized\r\n"

 ```

I can create a instance with open stack cli no problem. Below is the relevant kitchen bits

```
---
driver:
  name: openstack
  openstack_username: xx
  openstack_api_key: pass
  openstack_auth_url: url/v3/auth/tokens
  openstack_domain_name: domain
  image_ref: 0a0e6b50-d460-4b80-a6e6-4412df9da2e0
```

cheers.
rob
