### ISSUE TITLE
Same floating IP to different server

### ISSUE THREAD

**Issue by rlanore** [test-kitchen/kitchen-openstack#175]
Hi,

Concurrent background **kitchen create** get same floating IP from Openstack.
We don't want to use **-c** flags of kitchen.
We use gitlab-ci to do that and want one jobs per **bar**

```
cat test/test.sh 
kitchen create bar1 &
kitchen create bar2 &
kitchen create bar3 &
kitchen create bar4 &
kitchen create bar5 &
kitchen create bar6 &
kitchen create bar7 &
```

```
 Attaching floating IP <192.168.XX.196>
  Attaching floating IP <192.168.XX.163>
  Attaching floating IP <192.168.XX.154>
  Attaching floating IP <192.168.XX.154>
  Attaching floating IP <192.168.XX.171>
  Attaching floating IP <192.168.XX.171>
  Attaching floating IP <192.168.XX.171>
```

We use 

* Debian 9
* test-kithcen 1.18.0 
* kitchen-openstack 3.5.0

kitchen config file

```
---
driver:
  name: openstack
  openstack_username: ourusername
  openstack_api_key: ourkey
  openstack_auth_url: http://opentstack.ourdomain:5000/v2.0/tokens
  flavor_ref: m1.small
  network_ref: kitchen-net
  floating_ip_pool: net-xxxxx
  security_groups:
    - default
  openstack_tenant: kitchen
  private_key_path: ~/.ssh/id_key

transport:
  ssh_key: "~/.ssh/id_key"
  connection_timeout: 10
  connection_retries: 5
  username: root
  client_rb:
    node_name: analytics.local

provisioner:
  name: chef_zero
  chef_zero_host: 127.0.0.1
  require_chef_omnibus: 12.19.36-1
  chef_omnibus_url: 'http://xxxx.ourdomain/Chef/CHEF-CLIENTS/install.sh'
  roles_path: '~/.chef/roles'
  environments_path: '~/.chef/environments'
  data_bags_path: '~/.chef/data_bags'

platforms:
  - name: bar7
    driver_config:
      image_ref: bar7
  - name: bar6
    driver_config:
      image_ref: bar6
  - name: bar5
    driver_config:
      image_ref: bar5
  - name: bar4
    driver_config:
      image_ref: bar4
  - name: bar3
    driver_config:
      image_ref: bar3
  - name: bar1
    driver_config:
      image_ref: bar1
  - name: bar2
    driver_config:
      image_ref: bar2

suites:
  - name: gr
    run_list:
      - recipe[bar::foo]

```
