### ISSUE TITLE
block_device_mapping crashes on nodename nor servname provided

### ISSUE THREAD

**Issue by cvakiitho** [test-kitchen/kitchen-openstack#176]
When trying to create block storage device I'm getting following error: 

Attachment of existing device works fine.
```
-----> Creating <default-rhel-7-amd64-vmware>...
D      Selected image: 423423 rhel-7-amd64-vmware
D      Selected flavor: 20 m1.small
D      Selected net: 234234234asfasdf as asdfasdf
       Creating Volume...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Create failed on instance <default-rhel-7-amd64-vmware>.  Please see .kitchen/logs/default-rhel-7-amd64-vmware.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: 1 actions failed.
>>>>>>     Create failed on instance <default-rhel-7-amd64-vmware>.  Please see .kitchen/logs/default-rhel-7-amd64-vmware.log for more details
D      ----------------------
D      ------Backtrace-------
D      /Users/i337562/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:183:in `report_errors'
D      /Users/i337562/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:174:in `run_action'

....


/Users/i337562/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
D      /Users/i337562/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      ----End Backtrace-----
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: getaddrinfo: nodename nor servname provided, or not known (SocketError)
D      ----------------------
D      ------Backtrace-------
D      /Users/i337562/.chefdk/gem/ruby/2.4.0/gems/kitchen-openstack-3.5.0/lib/kitchen/driver/openstack.rb:103:in `rescue in create'
D      /Users/i337562/.chefdk/gem/ruby/2.4.0/gems/kitchen-openstack-3.5.0/lib/kitchen/driver/openstack.rb:77:in `create'
D      /Users/i337562/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:460:in `public_send'
D      /Users/i337562/.chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:460:in `block in perform_action'
```

my config:

```
---
driver:
  name: openstack
driver_config:
  openstack_username: <%= ENV['OS_USERNAME'] %>
  openstack_api_key: <%= ENV['OS_PASSWORD']%> # AKA your OpenStack Password
  openstack_auth_url: <%= ENV['OS_AUTH_URL']%>/auth/tokens 
  openstack_domain_name: <%= ENV['OS_PROJECT_DOMAIN_NAME'] %>
  openstack_project_name: <%= ENV['OS_PROJECT_NAME'] %>
  openstack_region: <%= ENV['OS_REGION_NAME'] %>
  openstack_tenant_name: <%= ENV['OS_PROJECT_NAME'] %>

  image_ref: rhel-7-amd64-vmware
  flavor_ref: 20
  key_name: "kitchen"
  read_timeout: 180
  write_timeout: 180
  connect_timeout: 180

  block_device_mapping:
    make_volume: true
    device_name: vda
    volume_size: 5
    delete_on_termination: false
    creation_timeout: 120
    availability_zone: <%= ENV['OS_REGION_NAME'] %>
```

server_name / server_name_prefix has no influence on the error whatsoever.
kitchen runs fine otherwise.
driver/openstack.rb:77 seems to just set server_name config, so I have no idea what is wrong.

**Comment by cvakiitho** [comment]
Oh, my Bad, 

I thought it should be creating device when you select make_volume: true -

So I guess it works as expected - failing without volume_id, maybe it could return better error message when you don't specify it.

**Comment by jjasghar** [comment]
Yeah, the error messaging isn't as friendly as anyone would like. Good to see that you figured it out though.

**Comment by cvakiitho** [comment]
@jjasghar sorry to spam you more, but I don't think that make_volume from snapshot is working for me. 

```
   block_device_mapping:
     make_volume: true
     volume_size: 5
     snapshot_id: 9c5e802e-9339-4cd6-aa20-b5f95e322fd8
     device_name: /dev/sdb
     delete_on_termination: true
     creation_timeout: 120
     availability_zone: eu-de-1a
```

Fails with same error as above. can it be something about our openstack api?

Is there a way to get more detailed log then --log-level debug?

Thanks,
Tomas
