### ISSUE TITLE
private method `select' called for nil:NilClass

### ISSUE THREAD

**Issue by Lasering** [test-kitchen/kitchen-openstack#177]
Using:

- ChefDK - 2.3.4.
- Kitchen - 1.17.0
- Kitchen Openstack - 3.5.0
- python-openstackclient - 3.12.0

I get the following error:

```
I, [2017-11-13T14:04:10.206097 #13055]  INFO -- proxy-proxy: -----> Creating <proxy-proxy>...
I, [2017-11-13T14:04:14.557951 #13055]  INFO -- proxy-proxy: OpenStack instance with ID of <292ee7c3-edf2-478a-add6-34333d1f2be1> is ready.
I, [2017-11-13T14:04:28.146348 #13055]  INFO -- proxy-proxy: Waiting for network information to be available...
E, [2017-11-13T14:04:28.443579 #13055] ERROR -- proxy-proxy: Create failed on instance <proxy-proxy>.
E, [2017-11-13T14:04:28.443862 #13055] ERROR -- proxy-proxy: ------Exception-------
E, [2017-11-13T14:04:28.443924 #13055] ERROR -- proxy-proxy: Class: NoMethodError
E, [2017-11-13T14:04:28.443961 #13055] ERROR -- proxy-proxy: Message: private method `select' called for nil:NilClass
E, [2017-11-13T14:04:28.443993 #13055] ERROR -- proxy-proxy: ----------------------
E, [2017-11-13T14:04:28.444023 #13055] ERROR -- proxy-proxy: ------Backtrace-------
E, [2017-11-13T14:04:28.444053 #13055] ERROR -- proxy-proxy: /home/simon/.chefdk/gem/ruby/2.4.0/gems/kitchen-openstack-3.5.0/lib/kitchen/driver/openstack.rb:373:in `filter_ips'
E, [2017-11-13T14:04:28.444084 #13055] ERROR -- proxy-proxy: /home/simon/.chefdk/gem/ruby/2.4.0/gems/kitchen-openstack-3.5.0/lib/kitchen/driver/openstack.rb:357:in `get_ip'
E, [2017-11-13T14:04:28.444115 #13055] ERROR -- proxy-proxy: /home/simon/.chefdk/gem/ruby/2.4.0/gems/kitchen-openstack-3.5.0/lib/kitchen/driver/openstack.rb:99:in `create'
E, [2017-11-13T14:04:28.444149 #13055] ERROR -- proxy-proxy: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:460:in `public_send'
E, [2017-11-13T14:04:28.444181 #13055] ERROR -- proxy-proxy: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:460:in `block in perform_action'
E, [2017-11-13T14:04:28.444212 #13055] ERROR -- proxy-proxy: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
E, [2017-11-13T14:04:28.444243 #13055] ERROR -- proxy-proxy: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:489:in `block in action'
E, [2017-11-13T14:04:28.444273 #13055] ERROR -- proxy-proxy: /opt/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
E, [2017-11-13T14:04:28.444305 #13055] ERROR -- proxy-proxy: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:488:in `action'
E, [2017-11-13T14:04:28.444336 #13055] ERROR -- proxy-proxy: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:460:in `perform_action'
E, [2017-11-13T14:04:28.444375 #13055] ERROR -- proxy-proxy: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:370:in `create_action'
E, [2017-11-13T14:04:28.444420 #13055] ERROR -- proxy-proxy: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:359:in `block in transition_to'
E, [2017-11-13T14:04:28.444453 #13055] ERROR -- proxy-proxy: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:358:in `each'
E, [2017-11-13T14:04:28.444483 #13055] ERROR -- proxy-proxy: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:358:in `transition_to'
E, [2017-11-13T14:04:28.444514 #13055] ERROR -- proxy-proxy: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:124:in `create'
E, [2017-11-13T14:04:28.444545 #13055] ERROR -- proxy-proxy: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/command.rb:197:in `public_send'
E, [2017-11-13T14:04:28.444576 #13055] ERROR -- proxy-proxy: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2017-11-13T14:04:28.444606 #13055] ERROR -- proxy-proxy: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2017-11-13T14:04:28.444637 #13055] ERROR -- proxy-proxy: ----End Backtrace-----

```

My `.kitchen.yml` is:

```
driver:
  name: openstack
  openstack_auth_url: <%= ENV['OS_AUTH_URL'] %>/auth/tokens
  openstack_domain_name: <%= ENV['OS_USER_DOMAIN_NAME'] %>
  openstack_region: <%= ENV['OS_REGION_NAME'] %>
  openstack_project_id: <%= ENV['OS_PROJECT_ID'] %>
  openstack_username: <%= ENV['OS_USERNAME'] %>
  openstack_api_key: <%= ENV['OS_API_KEY'] %>
  openstack_network_name: n-<%= ENV['OS_PROJECT_NAME'] %>
  flavor_ref: t1.medium
  image_ref: 69fd3f4f-6f91-4ec6-8055-39de857061f5 # CentOS-7-x86_64-GenericCloud-1706
  key_name: kitchen
  user_data: .hostname-fixer.sh

transport:
  ssh_key: .kitchen.pem
  username: centos

platforms:
  - name: proxy

suites:
  - name: proxy
    run_list:
      - recipe[dsi-artifacts-repo::proxy]
```

However If I assign it a floating ip:

```
platforms:
  - name: proxy
    driver:
      floating_ip_pool: provider
```

It works correctly.
