### ISSUE TITLE
Set a fixed IP address in the kitchen.yml

### ISSUE THREAD

**Issue by som3guy** [test-kitchen/kitchen-openstack#187]
Goal:
Set a specific fixed IP address from a private subnet that already exists in openstack.

I have tried a number of methods like:
``` yaml
driver:
      port:
        - subnet_id: 245bd6e1-2bf0-4dd9-8a88-be1b8cd357d2
          ip_address: 192.168.1.200
```
``` yaml
networks.fixed_ip: 192.168.1.200
```

I could list many more, but none were successful

Using virutalbox I would just use:
```yaml
driver:
  network:
     - ['private_network', {ip: '192.168.1.200'}]
```

I am not sure how to get that same functionality using the openstack driver or if it is possible.

It seems that you can do anything that fog-openstack can do with kithcen-openstack. And fog-openstack can do anything that the openstack API can do. So think I am just missing something.
