### ISSUE TITLE
Unable to create instance using network_ref

### ISSUE THREAD

**Issue by dschlenk** [test-kitchen/kitchen-openstack#42]
My .kitchen.yml includes

```

---
driver: 
  name: openstack
  openstack_username: david.schlenk
  openstack_api_key: XXXXXXX
  openstack_auth_url: http://172.17.20.2:5000/v2.0/tokens
  require_chef_omnibus: latest
  image_ref: CentOS 6.5 x86_64
  flavor_ref: m1.small
  private_key_path: ~/.ssh/david-schlenk.pem
  username: ec2-user
  openstack_tenant: DevOps
  floating_ip_pool: prov_flat_net
  network_ref: 6fc730d8-8a81-4289-b1f2-8046b93b3938
```

But attempting to run kitchen create results in:

```
-----> Starting Kitchen (v1.2.1)
-----> Creating <default-centos-64>...
>>>>>> Create failed on instance <default-centos-64>.
>>>>>> Please see .kitchen/logs/default-centos-64.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Expected([200, 202]) <=> Actual(400 Bad Request)
  response => #<Excon::Response:0x000000030bd2d8 @data={:body=>"{\"badRequest\": {\"message\": \"Multiple possible networks found, use a Network ID to be more specific.\", \"code\": 400}}", :headers=>{"Content-Length"=>"115", "Content-Type"=>"application/json; charset=UTF-8", "X-Compute-Request-Id"=>"req-131e095d-eb3c-4796-a240-c165dae60075", "Date"=>"Mon, 03 Mar 2014 20:37:06 GMT"}, :status=>400, :remote_ip=>"172.17.20.2"}, @body="{\"badRequest\": {\"message\": \"Multiple possible networks found, use a Network ID to be more specific.\", \"code\": 400}}", @headers={"Content-Length"=>"115", "Content-Type"=>"application/json; charset=UTF-8", "X-Compute-Request-Id"=>"req-131e095d-eb3c-4796-a240-c165dae60075", "Date"=>"Mon, 03 Mar 2014 20:37:06 GMT"}, @status=400, @remote_ip="172.17.20.2">
```

I've also tried specifying `network_ref` by name  and also using `openstack_network_name` instead of `network_ref` as well as not defining a network at all which all gave a similar error. Fresh install of kitchen-openstack via gem today. Ideas?
