### ISSUE TITLE
Message: cannot copy directory

### ISSUE THREAD

**Issue by kojiwell** [test-kitchen/kitchen-openstack#43]
I get this error message, which is probably because my local user and local home are different from the instance's.

```
Message: cannot copy directory /path/to/home/myuser/Documents/workspace/chef/cookbooks/myproject/default-ubuntu-1204-sandbox-20140322-26415-XXXXXX to itself /path/to/home/myuser/Documents/workspace/chef/cookbooks/myproject/default-ubuntu-1204-sandbox-20140322-26415-XXXXXX/cookbooks/myproject/default-ubuntu-1204-sandbox-20140322-26415-XXXXXX
```

My guess is, if I set the right driver option for the destination directory, this should be resolved, but I don't find it yet... 

Any help would be great!

.kitchen.yml:

```
driver:
  name: openstack
  openstack_username: <%= ENV['OS_USERNAME'] %>
  openstack_api_key: <%= ENV['OS_PASSWORD'] %>
  openstack_auth_url: <%= "#{ENV['OS_AUTH_URL']}/tokens" %>
  require_chef_omnibus: latest
  image_ref: <%= ENV['OS_IMAGE_ID'] %>
  flavor_ref: <%= ENV['OS_FLAVOR_ID'] %>
  key_name: <%= ENV['OS_KEY_NAME'] %>
  tenant_name: <%= ENV['OS_TENANT_NAME'] %>
  username: ubuntu

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04

suites:
  - name: myproject
    run_list:
      - recipe[myproject]
    attributes:
```

Version:

```
$ gem list | grep kitchen
kitchen-openstack (1.3.0)
test-kitchen (1.2.1)
```
