### ISSUE TITLE
Kitchen converge hangs

### ISSUE THREAD

**Issue by dchrzascik** [test-kitchen/kitchen-openstack#71]
Hello,

I'm facing a problem when creating a kitchen controlled instance on openstack. To be more specific, after instance is created (and availalbe via ssh, visible in openstack dashboard) the provisioning process hangs, chef-client is not initialized on instance. The same happens when using solely kitchen create, hence, I assume that for some reason vm creation process from kitchen perspective cannot be completed.

```
$kitchen converge -l debug
-----> Starting Kitchen (v1.2.1)
D      Berksfile found at /home/d.chrzascik/projects/esti/b2b-platform-env-manager/cookbooks/b2b-platform-common/Berksfile, loading Berkshelf
D      Berkshelf 3.2.1 library loaded
-----> Creating <default-ubuntu-1404>...
D      Selected image: 77c63bbc-dc2d-450d-b9ed-309810302c19 SRPOL-Ubuntu-14-tmpl-v1
D      Selected flavor: 42e56235-d20e-4837-ad30-a1a9a28c7ee6 SRPOL-small
D      Selected net: a3f95393-ae3b-4a48-8a0b-78ad2bdc9dec b2b-platform-net
       OpenStack instance <0a07860c-65b8-4008-9805-3acac6431c3f> created.
.......       
(server ready)
       Attaching floating IP from <ext-net> pool
       Attaching floating IP <106.120.115.27>
D      Using floating ip: 106.120.115.27
       (ssh ready)
       Using public SSH key </home/d.chrzascik/.ssh/id_rsa.pub>
       Using private SSH key </home/d.chrzascik/.ssh/id_rsa>
       Setting up SSH access for key </home/d.chrzascik/.ssh/id_rsa.pub>
       Adding OpenStack hint for ohai
net.ssh.transport.session[25a745c]
net.ssh.transport.session[25a745c]
net.ssh.transport.server_version[25a6980]
net.ssh.transport.server_version[25a6980]
net.ssh.transport.server_version[25a6980]
tcpsocket[25a6fac]
tcpsocket[25a6fac]
net.ssh.transport.algorithms[259f9c8]
net.ssh.transport.algorithms[259f9c8]
tcpsocket[25a6fac]
tcpsocket[25a6fac]
net.ssh.transport.algorithms[259f9c8]
```

Fragment of my .kitchen.yml:
```
---
driver:
  name: openstack
  # API
  openstack_username: XXXX
  openstack_api_key: XXXX
  openstack_auth_url: http://<host:port>/v2.0/tokens
  require_chef_omnibus: 'true'

  # VMs
  image_ref: 77c63bbc-dc2d-450d-b9ed-309810302c19
  flavor_ref: 42e56235-d20e-4837-ad30-a1a9a28c7ee6
  security_groups:
    - b2b-platform
  network_ref:  b2b-platform-net
  server_name_prefix: kitchen
  floating_ip_pool: ext-net
  no_ssh_tcp_check: true
  no_ssh_tcp_check_sleep: 30

  # Auth
  username: ubuntu
  password: XXX

provisioner:
  name: chef_solo
  environments_path: ../../environments

platforms:
  - name: ubuntu-14.04
```

Has anyone seen this behaviour before? What can I do?
